Products Logic Implementation
aemsites/octoral pull request #41
Opened 2024-08-04 21:17 UTC by meejain

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #35 

Test URLs:
- Before: https://main--octoral--aemsites.hlx.live/en/products/non-voc/mixing_colour_system/octobase_system_mixing_colours
- After: https://issue35-products-section--octoral--aemsites.hlx.live/en/products/non-voc/mixing_colour_system/octobase_system_mixing_colours

- Before: https://main-octoral--aemsites.hlx.live/en/products/non-voc/cleaning_agents
- After: https://issue35-products-section--octoral--aemsites.hlx.live/en/products/non-voc/cleaning_agents

- Before: https://main--octoral--aemsites.hlx.live/en/products/non-voc/mixing_colour_system
- After: https://issue35-products-section--octoral--aemsites.hlx.live/en/products/non-voc/mixing_colour_system

- Before: https://main--octoral--aemsites.hlx.live/en/products/non-voc/
- After: https://issue35-products-section--octoral--aemsites.hlx.live/en/products/non-voc/

2024-08-05 12:27 UTC, dave-fink commented on blocks/productstable/productstable.js
> +  showMoreCell.setAttribute('colspan', '100%');
You can leverage dom-helpers here!  36 & 37 can be combined into 1
`const showMoreCell = td({ colspan: '100%' });`

2024-08-06 13:33 UTC, dave-fink requested changes

2024-08-06 13:33 UTC, dave-fink commented on blocks/productstable/productstable.js
> +  const showLessRow = tr({ class: 'showless' });
Rather then add a showMore and a showLess row, you could make this one element.  Then handle the changing of the text in the click function.  Then all you need to do is add a class to the table itself and let CSS do the rest. No need to iterate over all the rows to show/hide them.  Leverage CSS parent child to show/hide.  Here's an example:

```
moreLessRow.addEventListener('click', () => {
  if (table.classList.contains('show-more')) {
    table.classList.remove('show-more');
    moreLessRow.textContent = 'Show More';
  } else {
    table.classList.add('show-move');
    moreOrLessRow.textContent = 'Show Less';
  }
});

2024-08-06 13:33 UTC, dave-fink commented on blocks/productstable/productstable.js
> +      if (i > 6 && !row.classList.contains('showmore')) {
If you leverage adding the class to the table, there's no need to add an additional hidden class here. You could just make this a data attribute like `data-row: 'expandable'.  Then your CSS could do all the work.

2024-08-06 13:33 UTC, dave-fink commented on templates/products/products.js
> +    cellhead1.textContent = 'Item nr.';
this can be one line -  `const cellhead1 = div({ class: 'heading' }, 'Item nr');`

2024-08-06 13:33 UTC, dave-fink commented on templates/products/products.js
> +
There appears to be a lot of duplication.  You could consider leveraging a helper function, perhaps something like this.  It is a little easier to read. 

```
results.forEach((result) => {
  // Create a new row for the table
  const trow = div();

  // Helper function to create and append a cell if the data exists
  const createCell = (data, cellClass) => {
    if (data) {
      const cell = div({ class: cellClass });
      cell.textContent = data;
      trow.append(cell);
    }
  };

  // Create and append each cell based on the result properties
  createCell(result.itemnr, 'data');
  createCell(result.code, 'data');
  createCell(result.productname, 'data');
  createCell(result.perbox, 'data');
  createCell(result.volume, 'data');

  // Append the row to the row list
  row.push(trowhead);
  row.push(trow);
});

2024-08-06 13:33 UTC, dave-fink commented on templates/products/products.js
> +      obj = new Obj(entry.type, entry['type-image'], entry['type-label'], entry.image, `/${locale}/products/${entry['voc-compliant']}/${entry.type.toLowerCase().replace(/ /g, '_')}/${entry.title.toLo
We do a lot of this `.toLowerCase().replace(/ /g, '_')`.  Let's leverage a utils function for normalizeString - I created one here - https://github.com/aemsites/octoral/pull/38/files#diff-0b21831cd9ed897d64279bd0b4bb242a206cbf2f949101967ca14dba17bb7dd4

2024-08-06 13:33 UTC, dave-fink commented on templates/products/products.js
> +  if (usedCase === 'stage3-card') {
It looks like 'stage1-card' and 'stage3-card' are the same - might be an opportunity to streamline this with an or operator.

2024-08-06 13:33 UTC, dave-fink commented on blocks/productstable/productstable.css
> +    background-color: var(--light-color);
small potatoes - but you can simply use `background` instead of `background-color`

2024-08-06 13:33 UTC, dave-fink commented on templates/products/products.css
> +.block.cards.products .cards-card-image p {
you could combine with line 9 

.block.cards.products .cards-card-body p, 
.block.cards.products .cards-card-image p {

or make a less specific selector
.block.cards.products p {

2024-08-06 13:33 UTC, dave-fink commented on templates/products/products.css
> +    }
Nesting look good.  Note, you can nest child elements too.  .cards-card-body could look like this.

```
.cards-card-body {
    margin: 0;
    padding: 0;
    position: absolute;
    z-index: 2;

    p {
      margin: 0;
      padding: 0;
    }

    .title {
      padding: 5px;
      text-decoration: underline;
    }
  }

2024-08-06 13:34 UTC, dave-fink commented on templates/products/products.js
> +      obj = new Obj(entry.type, entry['type-image'], entry['type-label'], entry.image, `/${locale}/products/${entry['voc-compliant']}/${entry.type.toLowerCase().replace(/ /g, '_')}/${entry.title.toLo
You can just copy that function into your PR - I'll close mine PR out.

2024-08-06 22:05 UTC, meejain commented on templates/products/products.js
> +      obj = new Obj(entry.type, entry['type-image'], entry['type-label'], entry.image, `/${locale}/products/${entry['voc-compliant']}/${entry.type.toLowerCase().replace(/ /g, '_')}/${entry.title.toLo
Fixed

2024-08-07 13:06 UTC, dave-fink approved these changes
Looks good!

2024-08-07 13:45 UTC, merged